numeros = [23123, 1313, 'terra', 456]
print(numeros[4])

'''
O error ocorre pq o índice informado não existe,
isso acontece pq os elementos de uma lista são contados a partir do zero e não do 1.
'''